### ISSUE TITLE
Default Logo and Brand name in wallet reload payment gateway window

### ISSUE THREAD

**Issue by rhlKumar** [urbanpiper/up-sdk-demo#1]
While loading wallet using UPSDK, the payment gateway page shows "Pipercafe" as brand name and logo instead of showing actual brand name and logo.
<img width="1280" alt="Screenshot 2020-11-07 at 6 12 39 PM" src="https://user-images.githubusercontent.com/7317605/98516515-9ed10480-2292-11eb-98cd-fcd5e4e275d2.png">

**Comment by jaaahh** [comment]
Please use upsdk.setPGConfig method to set the razorpay config,

```

let razorpay_options = {
	"currency": "INR",
	"name": "Pipercafe",
	"description": "Order payment",
	"image": "https://thepipercafe.com/images/logo.png?v=1.0",
	"theme": {
		"color": "#000"
	}
};

upsdk.setPGConfig("razorpay", razorpay_options)
```
