### ISSUE TITLE
No store object in .getStore(params), if the nearest store is shut or temporarily disabled.

### ISSUE THREAD

**Issue by rhlKumar** [urbanpiper/up-sdk-demo#2]
The customers needs to be shown a contextual error in below three cases:
1. No store found.
2. Store found but temporarily closed.
3. Store found but closed for the day.

However, the api does not return which is the case if there is an error. the fix would be to not return a store object in case #(default behaviour) and return the nearest store object for case #2 and #3 with the store status.

**Comment by rhlKumar** [comment]
@imjaah  Any update on this?

**Comment by jaaahh** [comment]
@rhlKumar please share the cURL
