### ISSUE TITLE
addCoupon doesn't work with guest checkout <Severe> 

### ISSUE THREAD

**Issue by rhlKumar** [urbanpiper/up-sdk-demo#4]
Hi Jaah. The addCoupon throws error "Please login and try again" when used to guest login. Below are the steps to reproduce the same. Please fix this on priority as our website is live and most of the users use guest checkout to place the order.

const a=UP_SDK;
let  c = a.checkoutSession({ fullfilmentmode: 'delivery' });
a.enableGuest({'phone':'8879426701', 'name':'Rahul Kumar'}).then(res=> {console.log(res); c.update({'phone':'8879426701'})})
let stores = a.getAllStores().then(res=> {stores=res.data})
c.setStore(stores[0])
let items  = c.getAllItems().then(res=>{items=res.data})
c.addToCart(items.items[0],1)
c.makeBill()
c.addCoupon({'coupon':'YPL50', 'phone':'8879426701'})

**Comment by rhlKumar** [comment]
Jaah, This is a priority issue as almost all of our customers use guest checkout flow..

**Comment by jaaahh** [comment]
@rhlKumar right now SDK doesn't support coupons in guest checkout.
we will add coupon support to SDK this week.

**Comment by rhlKumar** [comment]
@imjaah Thanks. Please let me know. I am reverting to the old website until then.

**Comment by jaaahh** [comment]
@rhlKumar fixed.
upsdk version: 4.85.0

**Comment by rhlKumar** [comment]
Working, Thanks.
